version: "3.4"

services:
  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  odoo:
    depends_on:
      - db
    image: odoo_asl_lite:12
    build:
      context: "."
    environment:
      PYTHONIOENCODING: UTF-8
      HOST: db
      USER: odoo
      PASSWORD: myodoo
    volumes:
      - odoo-data:/data
      - /etc/localtime:/etc/localtime:ro
      - ./addons_extra:/opt/addons_extra:ro
      - ./odoo.conf.local:/etc/odoo/odoo.conf:ro

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.odoo-asl.rule=Host(`odoo.developer.localhost`)"
      - "traefik.http.routers.odoo-asl.entrypoints=web-secure"
      - "traefik.http.routers.odoo-asl.tls=true"

volumes:
  db-data:
    driver: local
  odoo-data:
    driver: local
